auto-image-builder: remove quotes from podman command
Empty vars are passed to podman causing to error with
Error: reference parameter cannot be empty

Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>