bootc: Pass --network=none to bootc-image-builder podman
This should not need network access anyway, all the required
images are in local store. This is generally a good idea for
security, and also may fix running to-disk-image in CI where
there were some permission errors from netavark:

```
Writing manifest to image destination
internal:0:0-0: Error: Could not process rule: No such file or directory
internal:0:0-0: Error: Could not process rule: No such file or directory
Error: netavark: nftables error: "nft" did not return successfully while applying ruleset
```